# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:50:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class GetglobalnumberinfoGetResponse(BaseModel):
    Code: Optional[str] = None
    Country: Optional[str] = None
    Credits: Optional[str] = None
    Language2: Optional[str] = None
    Language3: Optional[str] = None
    Mobile: Optional[str] = None
    PrimaryCity: Optional[str] = None
    PrimaryLanguage: Optional[str] = None
    Region: Optional[str] = None
    Wealth: Optional[str] = None
